// All user-facing wording in this file is authored by Cowork and approved
// by Ken. Do not modify any string without Ken's explicit approval.
// This file is requested for the locked-files list in CLAUDE.md once shipped.

// ─── Milestone narrations (Path B only) ──────────────────────────────

export const MILESTONE_FOUNDATION_CONFIRMED =
  "OK, I've turned what you told me into the foundational message, what we call your Three Tier. Have a look at the top tier — that's the line we want your audience to remember. If it doesn't sound like you, tell me and we'll adjust.";

export const MILESTONE_CHAPTERS_SEPARATED_READY =
  "Now I've taken the foundation and split it into the five chapters of a story, what we call your 5 Chapter Story. I keep them separate at this stage so we can examine each one. Read them in order — they should feel like five connected steps, not five paragraphs.";

export const MILESTONE_CHAPTERS_COMBINED_READY =
  "I've joined the five chapters into one read so you can hear them as a single voice. It's still in pieces underneath — we can return to any one of them — but this is what your audience will experience.";

export const MILESTONE_BLENDED_READY =
  "Last pass: I've polished the seams so the five chapters feel like one piece of writing instead of five. This is the version you'd send. Take a look. If anything doesn't sound like you, point at it and we'll fix it.";

// ─── Soft notes for chapter content gaps (empty or partial) ──────────────
// Sent as separate chat messages after MILESTONE_BLENDED_READY, never
// appended to the deliverable body. One soft note per gappy chapter.

const CHAPTER_PURPOSE: Record<3 | 4 | 5, string> = {
  3: "ROI and measurable value",
  4: "others who already trust you",
  5: "what you want your audience to do next",
};

const EMPTY_CASE_FILL: Record<3 | 4 | 5, string> = {
  3: "any numerical metric",
  4: "an actual name or award",
  5: "a specific action they can take — a call link, an email, or a scheduling page",
};

// Round 4 Fix 9 — expanded from 5 to 10 entries so users don't see the
// same opening word for soft note 1 across multiple builds in a session.
export const VALUE_CLAIM_POOL: ReadonlyArray<string> = [
  "more compelling",
  "more persuasive",
  "sharper",
  "more direct",
  "stronger",
  "tighter",
  "clearer",
  "more memorable",
  "more concrete",
  "more credible",
];

// Internal counter for index-rotating selection. Module-level state.
let _valueClaimIdx = 0;
function pickValueClaim(): string {
  const claim = VALUE_CLAIM_POOL[_valueClaimIdx % VALUE_CLAIM_POOL.length];
  _valueClaimIdx += 1;
  return claim;
}

export function buildSoftNote(
  chapter: 3 | 4 | 5,
  missingPieces: string[]  // empty = whole chapter empty; non-empty = partial
): string {
  const purpose = CHAPTER_PURPOSE[chapter];
  const valueClaim = pickValueClaim();

  // Round 3.2 Item 4 — strip trailing punctuation from each piece before
  // joining. Some classifier outputs end with a period; the template
  // appends its own period after `${missingDescription}`, producing the
  // doubled-period bug Cowork observed (".. Anything I can use?").
  // Round 3.4 Bug 12 — dedupe pieces case-insensitively. Pat's verification
  // surfaced "with X and X. Anything I can use?" — the classifier returned
  // the same description twice in missingPieces. Drop exact-match repeats
  // before joining so the join template can't produce "and X and X".
  const cleaned = missingPieces.map(p => p.replace(/[.!?]+\s*$/, '').trim()).filter(p => p.length > 0);
  const seen = new Set<string>();
  const cleanedPieces: string[] = [];
  for (const p of cleaned) {
    const key = p.toLowerCase();
    if (seen.has(key)) continue;
    seen.add(key);
    cleanedPieces.push(p);
  }

  let missingDescription: string;
  if (cleanedPieces.length === 0) {
    missingDescription = EMPTY_CASE_FILL[chapter];
  } else if (cleanedPieces.length === 1) {
    missingDescription = cleanedPieces[0];
  } else if (cleanedPieces.length === 2) {
    missingDescription = `${cleanedPieces[0]} and ${cleanedPieces[1]}`;
  } else {
    const last = cleanedPieces[cleanedPieces.length - 1];
    const rest = cleanedPieces.slice(0, -1).join(", ");
    missingDescription = `${rest}, and ${last}`;
  }

  let question = `The chapter on ${purpose}, chapter ${chapter}, would be ${valueClaim} with ${missingDescription}. Anything I can use?`;

  // Round 3.4 Bug 12 — post-generation regex check. Belt-and-suspenders
  // against the duplicate-span case the classifier-dedup above doesn't
  // catch (e.g. near-duplicate phrases that differ only in casing or
  // whitespace). Pattern: any 20+-character span repeated consecutively
  // (with up to 3 connector words / whitespace between). When detected,
  // collapse the span to one occurrence rather than re-running the call —
  // re-rolling here is impractical because the enrichment question is
  // assembled deterministically from missingPieces, not generated by an
  // LLM at this layer.
  const dupSpanPattern = /(\b.{20,}?\b)\s+(?:and|,|\.|;|\s){0,15}\1/i;
  const m = dupSpanPattern.exec(question);
  if (m) {
    // Collapse the second occurrence to nothing, leaving a clean sentence.
    question = question.replace(dupSpanPattern, m[1]);
    console.log('[buildSoftNote] dropped duplicate clause (Bug 12 guard)');
  }

  return question;
}

// ─── Mode-switch offer (Path A → Path B, after 3 consecutive what's-next) ─

export const MODE_SWITCH_OFFER_PATH_A_TO_B =
  "Want me to take the lead from here? I'll narrate the next moves as we go.";

export const MODE_SWITCH_OFFER_CHIP_YES = "Yes, take the lead";
export const MODE_SWITCH_OFFER_CHIP_NO  = "No, I'll keep going";

// ─── Toggle confirmations (fire on every flip event, in or out of pipeline) ─

export const TOGGLE_CONFIRMATION_ON =
  "Got it — taking over from here.";

export const TOGGLE_CONFIRMATION_OFF =
  "Got it. Back to you. I'll still be here for any edit requests or reviews anytime you ask.";

// ─── Foundational-shift pause (mid-pipeline, after a foundation-changing edit) ─

export const PAUSE_ON_FOUNDATIONAL_SHIFT =
  "Hold on — let me redo the foundation with that change before I keep going.";

// ─── Foundational-shift timeout (Path B, 5-min hold expired) ──────────

export const TIMEOUT_AREA_TIER1     = "your top tier";
export const TIMEOUT_AREA_TIER2     = "your priorities";
export const TIMEOUT_AREA_AUDIENCE  = "your audience";
export const TIMEOUT_AREA_OFFERING  = "your offering";
export const TIMEOUT_AREA_FALLBACK  = "the foundation";

export function buildFoundationalShiftTimeout(area: string): string {
  return `I had to let the story go — I can only hold things for a few minutes. When you're ready to come back to ${area}, tell me and we'll start it back up.`;
}

// ─── Fresh-user opener (empty workspace, on direct invocation of chat) ────

export const OPENER_FRESH_USER =
  "Hi — I'm Maria. What are we working on?";

// ─── Fresh-user opener chips (paired with OPENER_FRESH_USER) ────────────

export const OPENER_FRESH_USER_CHIPS: ReadonlyArray<string> = [
  "Win over a customer or outside audience",
  "Get sign-off from a decision-maker inside",
  "Align a team on a move",
  "Sharpen a draft I've already started",
];

// ─── iPhone affordance labels ─────────────────────────────────────────

export const IPHONE_AFFORDANCE_TAKE_A_LOOK = "Take a look";
export const IPHONE_AFFORDANCE_WORK_WITH_MARIA = "Work with Maria";

// ─── Tunable constants ────────────────────────────────────────────────

export const PAGE_AFTER_NARRATION_DELAY_MS = 1000;
export const WHATS_NEXT_TRIGGER_THRESHOLD = 3;

// ─── What's-next detector intent list ─────────────────────────────────

export const WHATS_NEXT_INTENT_PHRASES: ReadonlyArray<string> = [
  "what's next",
  "whats next",
  "what now",
  "now what",
  "what should i do",
  "what do i do next",
  "where do we go from here",
  "what's the next step",
  "keep going",
  "let's keep going",
  "go on",
  "continue",
];

// ─── Skip-demand response (user explicitly asks to bypass coaching) ─────
// Round 4 Fix 4 — Ken's tightened four-sentence version. Replaces the
// prior five-sentence text which read as a wall on phones.

export const SKIP_DEMAND_RESPONSE =
  "I've tried this — it doesn't work well. The result is more persuasive if you confirm interim steps. I'll help. But if you really want to skip, I'll do my best with what you've given me. It'll take a few minutes.";

export const SKIP_DEMAND_CHIP_CONTINUE = "Lead me through interim steps. Quickly.";
export const SKIP_DEMAND_CHIP_AUTONOMOUS = "I understand. Do your best.";

export const SKIP_INTENT_PHRASES: ReadonlyArray<string> = [
  "just build it",
  "just build the whole thing",
  "skip the process",
  "skip the questions",
  "skip the steps",
  "skip ahead",
  "skip it",
  "i don't want to do this",
  "i don't want to walk through",
  "give me the result",
  "give me the deliverable",
  "do it for me",
  "do the whole thing",
  "go ahead and do it",
  "build the whole thing",
];

// ─── Stage-aware presence check-ins (fire if a stage runs > 30s) ─────

export const STAGE_CHECKIN_TIER_GENERATION =
  "Working on the foundation — won't be long.";

export const STAGE_CHECKIN_CHAPTERS =
  "Working through the chapters — should be a couple minutes.";

export const STAGE_CHECKIN_BLEND =
  "Polishing the seams — almost there.";

// ─── Foundational-shift hold midpoint presence (fires at 90s of 3-min hold) ──

export const FOUNDATIONAL_SHIFT_HOLD_MIDPOINT =
  "Still here — take your time.";

// ─── Fallback chat-open opener when the validator catches a fabricated name ─
// Round 4 Fix 1.

export const OPENER_FALLBACK_GENERIC =
  "Welcome back. What are we working on today?";

// ─── Soft-note pacing — Round 4 Fixes 7 + 8 ────────────────────────────
// After MILESTONE_BLENDED_READY lands, wait this long before writing the
// first soft note so Maria's "Take a look" invitation has breathing room.
export const PAUSE_BEFORE_SOFT_NOTES_MS = 4000;
// Between soft notes, when more than one chapter has gaps. Prevents the
// chat panel from queue-dumping bubbles all at once.
export const SOFT_NOTE_STAGGER_MS = 3500;

// ─── Path A dashboard banner — Round 4 Fix 10 ──────────────────────────
// Replaces the prior "You're driving. I'll wait until you ask." banner.
// Stylized capital-L "Let Maria Lead" is intentional — the live toggle
// label uses lowercase but the banner reference reads as a setting name.

export const PATH_A_BANNER =
  "Maria is listening. Toggle 'Let Maria Lead' for guidance.";

// ─── Round 3.1 Item 2 — Autonomous skip-demand pipeline messages ───────
// Templates take the user's stated deliverable type ("email", "pitch
// deck", "landing page", etc.). The same word substitutes into every
// slot of a given message — never mix "email" and "draft" inside one
// post-delivery offer. If the deliverable type is unknown, callers
// should fall back to "deliverable" verbatim.

// Round 3.4 Bug 3 — every interpolation of deliverableType is routed through
// mediumDisplayLabel so the human-readable label ("pitch deck") substitutes
// in Maria's voice instead of the snake_case enum ("pitch_deck"). The label
// helper is defined later in this file; forward-reference is fine in TS
// because mediumDisplayLabel is a function declaration.
export function buildAutonomousPreBuildExpectation(deliverableType: string): string {
  const label = mediumDisplayLabel(deliverableType);
  return `I'll be doing multiple things with the info you've given me to create the ${label} — this will take a few minutes.`;
}

export function buildAutonomousPostDeliveryOffer(deliverableType: string): string {
  const label = mediumDisplayLabel(deliverableType);
  return `This is the ${label} you asked for. Quick context: to write it I built a reusable foundation underneath — a Three Tier — and the deliverable came out of that. If anything in the ${label} feels off, the Three Tier is the place to fix it, not the ${label} itself. Take me there to review?`;
}

export const AUTONOMOUS_POST_DELIVERY_CHIP_YES =
  "Yes, take me to the Three Tier";

export function buildAutonomousPostDeliveryChipNo(deliverableType: string): string {
  const label = mediumDisplayLabel(deliverableType);
  return `No, I'll review the ${label} here`;
}

// Bundle 1A rev2 W4 — autonomous-build completion message. After Maria
// fires build_deliverable in autonomous (Path B) mode and the pipeline
// finishes, the chat needs a hand-off message so the user knows the
// build completed and where to find the deliverable. Locked Cowork
// copy: surfaces the deliverable location without auto-navigating —
// Path B keeps the chat as the primary surface, the user opens the
// deliverable when they're ready.
export const AUTONOMOUS_BUILD_COMPLETE =
  "Done — your draft is ready. Open it from 3 Tiers or 5 Ch. Stories whenever you want a look.";

// Bundle 1A rev6 Phase 2.A — structural regeneration heartbeat. Fires
// AT MOST once per pipeline run when the methodology-gate retry phase
// (per-chapter regenerate after fiveChapterCheck failure) exceeds the
// 90-second threshold. Same shape as TIER_GENERATION_HEARTBEAT and
// CHAPTERS_HEARTBEAT.
export const STRUCTURAL_REGEN_HEARTBEAT =
  "Tightening up a couple of the chapters — won't be much longer.";

export const STRUCTURAL_REGEN_HEARTBEAT_MS = 90000;

// Bundle 1A rev6 Phase 2.A — methodology-failure chat message. Fires
// when fiveChapterCheck retries exhaust without producing a passing
// chapter set. Maria's voice, specific gap explanation, no
// AUTONOMOUS_BUILD_COMPLETE follow-up. The deliverable is still
// persisted; the user can review it via 3 Tiers / 5 Ch. Stories from
// their workspace. Template parameterizes over the joined issueList
// (chapter violations + cross-check details from fcResult).
export function buildMethodologyFailureMessage(issueList: string): string {
  return `I built the five chapters, but the structural shape didn't quite land — ${issueList}. I'd rather we look at this together than ship something I'm not happy with. Want to walk through it?`;
}

// Bundle 1A rev7 Pair A — gap-notice-before-build copy. Fires before
// autonomous-build kicks off when Maria detects user data missing for
// a deliverable that needs it. Maria asks once, with a one-line reason
// for why filling the gap makes the message stronger. Dismissal chip
// lets the user proceed without filling the gap; the deliverable
// then renders a graceful default rather than a placeholder string.
//
// Rule 1 — display-name gap. Triggered when User.name is empty/null
// AND medium is email (the medium with a sign-off requirement). The
// fall-through close is the literal text the email signs with when
// the gap is dismissed or the user has no name on file.
export const GAP_NOTICE_DISPLAY_NAME =
  "What name goes on this? Yours reads stronger than a generic close.";
export const GAP_NOTICE_DISPLAY_NAME_CHIP_DISMISS = "Skip — no name";
export const GAP_NOTICE_DISPLAY_NAME_FALLTHROUGH_CLOSE = "Best regards";

// Rule 3 — Support-gap notice. Triggered when the source Three Tier
// has no Support-category Tier 2 with substantive content (text +
// non-empty tier3Bullets). The fall-through Ch3 line is the literal
// text Ch3 reads when the gap is dismissed; per Cowork the support
// arrangement gets defined in scoping rather than padded into prose.
export const GAP_NOTICE_SUPPORT =
  "I don't see how you actually back the buyer up once they say yes. Tell me one or two concrete ways — training, weekly check-ins, a dedicated person — so the email shows real support, not just promises.";
export const GAP_NOTICE_SUPPORT_CHIP_DISMISS = "Skip — figure out support later";
export const GAP_NOTICE_SUPPORT_FALLTHROUGH_CH3 =
  "We'll define the implementation path with you in scoping.";

// ─── Round 3.1 Item 3 — Blend-phase heartbeat ──────────────────────────
// Fires AT MOST once per blend run, when the blend stage exceeds
// BLEND_HEARTBEAT_MS. Suppressed if blend completes under the threshold.

export const BLEND_HEARTBEAT =
  "Still polishing — this last pass takes a minute.";

export const BLEND_HEARTBEAT_MS = 60000;

// ─── Round 3.3 Item 1 — tier-generation + chapters heartbeats ─────────
// Same pattern as BLEND_HEARTBEAT — fire AT MOST once per stage when
// elapsed exceeds the threshold. Round 3.2 surfaced 4-5 minute silent
// gaps between STAGE_CHECKIN and the next milestone; users staring at
// a silent chat close the tab. Cowork-locked wording.

export const TIER_GENERATION_HEARTBEAT =
  "Still on the foundation — getting the top tier right takes a beat.";

export const CHAPTERS_HEARTBEAT =
  "Still on the chapters — letting each one breathe before stitching them together.";

// Round 3.4 Bug 2 — tightened from 90000 → 60000 to satisfy Cowork's
// "60-second maximum heartbeat interval" rule. The earlier 90s threshold
// was set in Round 3.3 against unverified perf data; Cowork's live walk
// found the gap noticeable, so all three pipeline heartbeats now align
// at 60s.
export const TIER_GENERATION_HEARTBEAT_MS = 60000;
export const CHAPTERS_HEARTBEAT_MS = 60000;

// ─── Round 3.2 Item 3 — Splash welcome (fresh-signup dashboard) ────────
// Replaces the prior 47-word promotional splash. Same six words as
// OPENER_FRESH_USER — the splash and the chat-panel opener intentionally
// share this line to reduce visual noise on first impression.

export const SPLASH_FRESH_USER =
  "Hi — I'm Maria. What are we working on?";

// ─── Round 3.2 Item 5B — DROPPED per Cowork's verification call. ──────
// PATH_A_RETURN_ACKNOWLEDGMENTS and buildPathAReturnAcknowledgment were
// removed because Round 4 Fix 11's audience-anchored chat-open opener
// ("Back to the [audience]?") already covers return-user continuity
// for the same trigger condition. Adding a separate locked-pool layer
// on top competed with Fix 11 for the same chat-panel slot.

// ─── Round 3.2 Item 7 — Affirmation pool ──────────────────────────────
// Replaces the templated "That was actually really clear" tic. Maria
// chooses an entry only when an affirmation is warranted; many turns
// have no affirmation at all. Index-rotating selection, same shape as
// VALUE_CLAIM_POOL.

export const AFFIRMATION_POOL: ReadonlyArray<string> = [
  "Got it. That's enough to work with.",
  "OK — I have what I need on that.",
  "Right there — that's clean.",
  "Crisp. That helps.",
  "That tracks. Good enough to build on.",
  "Clear. Moving on.",
  "Solid. That's what I needed.",
  "Got it.",
];

let _affirmationIdx = 0;
export function pickAffirmation(): string {
  const a = AFFIRMATION_POOL[_affirmationIdx % AFFIRMATION_POOL.length];
  _affirmationIdx += 1;
  return a;
}

// ─── Round 3.2 Item 11 — Identity acknowledgment ──────────────────────
// Fires only when the user asks an identity question ("Are you AI?",
// "What model are you?", "Who built you?", similar). Maria answers
// directly, then bridges back to the work at hand on the next turn.

export const IDENTITY_ACKNOWLEDGMENT =
  "Yes, I'm an AI agent built by Anthropic and trained on techniques to help with persuasive messaging.";

// Phrase list for backend identity-question detection. Lean toward false
// negatives — if the user phrases the question off-list, Opus's normal
// flow continues; the rule-detect short-circuit only fires on clear hits.
export const IDENTITY_INTENT_PHRASES: ReadonlyArray<string> = [
  "are you ai",
  "are you a ai",
  "are you an ai",
  "are you human",
  "are you a human",
  "are you a person",
  "are you a bot",
  "are you a chatbot",
  "what model are you",
  "what model is this",
  "which model",
  "who built you",
  "who made you",
  "who created you",
  "what are you",
  "are you real",
];

// ═══════════════════════════════════════════════════════════════════════
// ROUND 3.4 — Cowork-authored locked copy (added 2026-05-01)
// ═══════════════════════════════════════════════════════════════════════

// ─── Bug 1 — Format question + chips (replaces inline list) ───────────
// Asked once per build, before pipeline kickoff, so Maria captures the
// canonical medium and routes the build correctly. The chip set IS the
// supported-medium inventory.

export const FORMAT_QUESTION =
  "Before I build, what format do you need? Pick whichever fits — I can build any of these.";

export const FORMAT_CHIPS: ReadonlyArray<string> = [
  "Email",
  "One-pager",
  "Pitch deck",
  "Landing page",
  "Sales script",
  "Other (let me describe)",
];

// Honest fallback when a stated medium is recognized but the export path
// for that medium is not yet implemented. Currently used for pitch deck
// (no .pptx export wired). Maria offers the closest supported medium.
export const PITCH_DECK_HONEST_FALLBACK =
  "That's a pitch deck request — I can write the words for every slide and structure them in pitch-deck order, but the export comes out as a structured doc rather than a true .pptx for now. Want me to build it that way, or would a one-pager land the same job for your meeting?";

export const PITCH_DECK_FALLBACK_CHIP_KEEP = "Build it that way";
export const PITCH_DECK_FALLBACK_CHIP_SWITCH = "Switch to one-pager";

// Human-readable display labels for each medium enum value. Single source
// of truth for any user-facing rendering of the canonical medium — Bug 3
// fix routes every interpolation through this map to prevent snake_case
// (pitch_deck, one_pager, etc.) from leaking into Maria's voice.
export const MEDIUM_DISPLAY: Record<string, string> = {
  email: "email",
  one_pager: "one-pager",
  pitch_deck: "pitch deck",
  landing_page: "landing page",
  sales_script: "sales script",
  blog_post: "blog post",
  report: "report",
  other: "deliverable",
  deliverable: "deliverable",
};

export function mediumDisplayLabel(medium: string | null | undefined): string {
  if (!medium) return "deliverable";
  const key = String(medium).trim().toLowerCase();
  return MEDIUM_DISPLAY[key] ?? key.replace(/_/g, " ");
}

// ─── Bug 2 — Long-operation heartbeat + check-in + stall recovery ─────

// Post-polish enrichment heartbeat. The enrichment phase (after the
// polished read, before Maria asks per-chapter follow-ups) had no
// heartbeat in Rounds 3.1–3.3 and is the silent gap Cowork's verification
// caught. Fires AT MOST once per enrichment run when the phase exceeds
// the threshold.
export const POST_POLISH_ENRICHMENT_HEARTBEAT =
  "Pulling together the last few questions for you — give me a moment.";
export const POST_POLISH_ENRICHMENT_HEARTBEAT_MS = 60000;

// Proactive check-in fired at 4 minutes of a single operation. Maria
// surfaces that things are taking longer than expected and invites the
// user to add anything mid-flight — the chat input must already be
// editable per Bug 2 sub-item 1.
export const LONG_OP_PROACTIVE_CHECKIN =
  "This one's taking a little longer than I expected. I'm still on it — if you want to add anything before I finish, type now and I'll fold it in.";
export const LONG_OP_PROACTIVE_CHECKIN_MS = 240000;

// Server-side stall threshold. If a pipeline operation has not produced
// a heartbeat or output for 6 minutes the server marks it stalled,
// releases any chat lock, and Maria sends PIPELINE_STALL_RECOVERY with
// the two recovery chips on the user's next session contact.
export const PIPELINE_STALL_THRESHOLD_MS = 360000;

export const PIPELINE_STALL_RECOVERY =
  "Something hung on my end on that last build. Nothing of yours is lost — your audience, offering, and tier statements are saved. Want me to pick up from where I was, or move to something else?";

export const PIPELINE_STALL_RECOVERY_CHIP_PICKUP = "Pick up where you were";
export const PIPELINE_STALL_RECOVERY_CHIP_NEW = "Start something else";

// ─── Bug 4 — Enrichment one-at-a-time intro + bridge ──────────────────

export const ENRICHMENT_INTRO =
  "Reading through it, three things would make this stronger. Let me ask you about them one at a time — starting with the one that matters most.";

// Spoken before each subsequent enrichment question after the first.
// Pair with the next-question text from the enrichment generator.
// Round 3.4 coaching bundle — exported under both ENRICHMENT_NEXT_BRIDGE
// (original) and ENRICHMENT_TRANSITION (Ken's bundle-spec name) so the
// wiring layer can use whichever it prefers.
export const ENRICHMENT_NEXT_BRIDGE = "Good. One more thing: ";
export const ENRICHMENT_TRANSITION = ENRICHMENT_NEXT_BRIDGE;

// ─── Bug 8 — Methodology vocabulary first-introduction explanations ──
// Used by coaching/partner prompts. The first time any of these terms
// surfaces in Maria's voice within a session, the prompt wraps the term
// with the explanation parenthetical. Subsequent uses are bare.
//
// Per-session "introduced" state lives outside this file (session-keyed
// Set on the partner/coaching call sites). This map is the source of
// the explanation copy only.

export const METHODOLOGY_TERM_EXPLANATIONS: Record<string, string> = {
  "Three Tier":
    "the foundational hierarchy of what your audience cares about, top to bottom",
  "Tier 1":
    "the single most important thing your audience needs to walk away believing",
  "Tier 2":
    "the supporting columns that back up the top tier",
  "Tier 3":
    "the bottom-of-the-hierarchy claims that need to be most concrete and verifiable",
  "Five Chapter Story":
    "a five-step narrative arc that turns the foundation into a piece a real audience reads",
  "Chapter 1":
    "the category-level setup, before your offering enters",
  "Chapter 2":
    "where your offering enters the story",
  "Chapter 3":
    "the ROI and measurable value chapter",
  "Chapter 4":
    "the customer-evidence chapter, problem to solution to result",
  "Chapter 5":
    "the call to action — what you want the audience to do next",
  "blend":
    "the pass where I stitch the five chapters into one continuous read",
  "polish":
    "the final pass where I tighten the seams so it reads as one voice",
};

export function buildFirstUseExplanation(term: string): string {
  const explanation = METHODOLOGY_TERM_EXPLANATIONS[term];
  if (!explanation) return term;
  return `${term} (${explanation})`;
}

// ─── Bug 11 — Empty Tier 2 row guidance + drop-row chip ───────────────

export const SOCIAL_PROOF_EMPTY_GUIDANCE =
  "Social proof is empty because I don't have a name to use yet. Add one or two customers you can reference — even just first name + role + company size — and this row fills in.";

export const DROP_EMPTY_ROW_CHIP = "Drop this row for now.";

// Round 3.4 coaching bundle — parameterized variant. Falls back to the
// social-proof copy when the empty row IS social proof, otherwise builds
// a row-category-specific guidance line in Cowork's voice. The category
// name should be the human-readable label (e.g., "Social proof", "ROI",
// "Support"), NOT the snake_case enum.
const TIER2_EMPTY_GUIDANCE_BY_CATEGORY: Record<string, string> = {
  "Social proof": SOCIAL_PROOF_EMPTY_GUIDANCE,
  "ROI":
    "ROI is empty because I don't have a measurable outcome yet. Tell me a number — even an order of magnitude estimate — and this row fills in.",
  "Support":
    "Support is empty because I don't know how you actually back up the buyer after the sale. Tell me what training, planning, or ongoing help you provide and this row fills in.",
  "Focus":
    "Focus is empty because I don't have your commitment-to-the-audience statement yet. Tell me, in your voice, what your company is committed to giving them — and this row fills in.",
  "Product":
    "Product is empty because I don't have your differentiating capabilities yet. Tell me one or two things your offering does that the alternatives don't — and this row fills in.",
};

export function buildTier2EmptyGuidance(categoryName: string): string {
  const trimmed = (categoryName || "").trim();
  if (TIER2_EMPTY_GUIDANCE_BY_CATEGORY[trimmed]) {
    return TIER2_EMPTY_GUIDANCE_BY_CATEGORY[trimmed];
  }
  // Generic fallback for any future category we haven't authored yet.
  return `${trimmed} is empty because I don't have what I need yet. Tell me what would go here, even briefly, and this row fills in.`;
}

// Bundle-spec alias — TIER2_EMPTY_GUIDANCE references the builder so
// callers can do TIER2_EMPTY_GUIDANCE("Social proof") at the call site.
export const TIER2_EMPTY_GUIDANCE = buildTier2EmptyGuidance;

// ─── Bug 13 — Example-deliverable ribbon ──────────────────────────────
// Rendered at the top of any deliverable created via Maria's "show me
// how" example walkthrough path. Visually distinct from real-work
// deliverables; dashboard recent-work tag also reads "EXAMPLE".

export const EXAMPLE_DELIVERABLE_RIBBON =
  "Example walkthrough — built to show you how Maria works. Not your real work.";

export const EXAMPLE_DELIVERABLE_DASHBOARD_TAG = "EXAMPLE";

export const EXAMPLE_DELIVERABLE_NEW_REAL_BUTTON = "Start something real";

// ─── Bug 14 — Suggested-answer chip framing ───────────────────────────
// Rendered above any group of chips that pre-populate content (as
// opposed to navigation chips like "Yes" / "No"). Cowork's decision is
// to keep these chips because they help users articulate things they
// take for granted — the framing makes clear the chip is a SHAPE, not
// a CLAIM, and the chip click inserts editable text into the input
// rather than auto-submitting.

export const SUGGESTED_ANSWER_CHIP_FRAMING =
  "Here are some shapes that often fit — pick one as a starting point if it sounds right, or type your own.";

// Bundle-spec alias name — SUGGESTED_CHIPS_FRAME points at the same
// string. Either export name works at call sites.
export const SUGGESTED_CHIPS_FRAME = SUGGESTED_ANSWER_CHIP_FRAMING;

// ─── New feature — Stuck-state detection re-engage copy ───────────────
// Six trigger types, one locked re-engage line per trigger. Some templates
// take parameters (the current question, the next-step purpose) and the
// caller substitutes them — explanation-style wording per Cowork.

export const STUCK_IDLE =
  "Still here whenever you're ready. If you're not sure what to say, just tell me what you're stuck on and I'll help you through it.";

export const STUCK_EMPTY_SUBMIT =
  "Looks like that one came through blank. No rush — type whatever's on your mind, even partial, and I'll work with it.";

export function buildStuckExplicitHelp(restateQuestion: string): string {
  return `Of course. Let's break this down. The question I'm asking is ${restateQuestion}. Want me to give you a couple of examples of what people usually say here?`;
}

export function buildStuckMetaQuestion(
  currentStepPurpose: string,
  nextStep: string
): string {
  return `Fair question. Right now I'm trying to understand ${currentStepPurpose}. Once I have that, I'll ${nextStep}. Does that help, or do you want me to back up?`;
}

export function buildStuckOffTopic(restateQuestion: string): string {
  return `Got it. To make sure I'm following — were you answering ${restateQuestion}, or were we shifting to something else? Either way is fine, just want to make sure we're on the same page.`;
}

export function buildStuckOneWordReply(concreteExample: string): string {
  return `Got that. Can you give me a sentence or two more? Something like ${concreteExample}.`;
}

// Idle threshold for the client-side timer that fires STUCK_IDLE when
// the user has been on an active question without typing or clicking.
export const STUCK_IDLE_MS = 90000;

// Pattern-match phrases for the explicit-help trigger. Lower-cased on
// the call site before comparing. Lean toward false negatives — Opus
// classification picks up the long tail.
export const STUCK_EXPLICIT_HELP_PHRASES: ReadonlyArray<string> = [
  "help",
  "i don't know",
  "i dont know",
  "idk",
  "i'm lost",
  "im lost",
  "i am lost",
  "what should i say",
  "what do i say",
  "i'm stuck",
  "im stuck",
  "i am stuck",
  "stuck",
];

// Pattern-match phrases for the meta-question trigger. Opus classifier
// picks up paraphrases; this list is the rule-fast-path for the common
// shapes Cowork heard live.
export const STUCK_META_QUESTION_PHRASES: ReadonlyArray<string> = [
  "what are you doing",
  "what's happening",
  "whats happening",
  "what is happening",
  "are you really listening",
  "are you listening",
  "do you understand me",
  "did you get that",
  "what's going on",
  "whats going on",
];
